In [87]:
import pandas as pd
import os

In [98]:
df_clients = pd.read_csv(r"..\data\raw\customers.csv", sep=';')
df_produits = pd.read_csv(r"..\data\raw\products.csv", sep=';')
df_ventes = pd.read_csv(r"..\data\raw\Transactions.csv", sep=';')

C:\Users\trist\AppData\Local\Temp\ipykernel_26552\1689724477.py:3: DtypeWarning: Columns (0,1,2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ventes = pd.read_csv(r"..\data\raw\Transactions.csv", sep=';')

In [101]:
df_clients.describe()

             birth
count  8621.000000
mean   1978.275606
std      16.917958
min    1929.000000
25%    1966.000000
50%    1979.000000
75%    1992.000000
max    2004.000000

In [100]:
df_produits.describe()

             price        categ
count  3286.000000  3286.000000
mean     21.863597     0.370359
std      29.849786     0.615446
min       0.620000     0.000000
25%       6.990000     0.000000
50%      13.075000     0.000000
75%      22.990000     1.000000
max     300.000000     2.000000

In [99]:
df_ventes.describe()

       id_prod                        date session_id client_id
count   687534                      687534     687534    687534
unique    3265                      687419     345505      8600
top      1_369  2021-10-13 17:05:59.572162   s_118668    c_1609
freq      2340                           2         14     25586

In [92]:
df_ventes = df_ventes.dropna(how='all')

In [93]:
df_clients.head()

  client_id sex  birth
0    c_4410   f   1967
1    c_7839   f   1975
2    c_1699   f   1984
3    c_5961   f   1962
4    c_5320   m   1943

In [94]:
df_produits.head()

  id_prod  price  categ
0  0_1421  19.99      0
1  0_1368   5.13      0
2   0_731  17.99      0
3   1_587   4.99      1
4  0_1507   3.99      0

In [95]:
df_ventes.head()

  id_prod                        date session_id client_id
0  0_1259  2021-03-01 00:01:07.843138        s_1     c_329
1  0_1390  2021-03-01 00:02:26.047414        s_2     c_664
2  0_1352  2021-03-01 00:02:38.311413        s_3     c_580
3  0_1458  2021-03-01 00:04:54.559692        s_4    c_7912
4  0_1358  2021-03-01 00:05:18.801198        s_5    c_2033

In [96]:
df_inter = df_clients.merge(df_ventes, on='client_id', how='inner')
df = df_inter.merge(df_produits, on='id_prod', how='inner')

In [97]:
df

,client_id,sex,birth,id_prod,date,session_id,price,categ
0,c_4410,f,1967,1_483,2021-03-13 21:35:55.949042,s_5913,15.99,1
1,c_4410,f,1967,0_1111,2021-03-22 01:27:49.480137,s_9707,19.99,0
2,c_4410,f,1967,1_385,2021-03-22 01:40:22.782925,s_9707,25.99,1
3,c_4410,f,1967,0_1455,2021-03-22 14:29:25.189266,s_9942,8.99,0
4,c_4410,f,1967,0_1420,2021-03-22 22:31:25.825764,s_10092,11.53,0
...,...,...,...,...,...,...,...,...
687529,c_84,f,1982,0_1472,2022-05-14 00:24:49.391917,s_208110,12.49,0
687530,c_84,f,1982,0_1438,2022-05-29 06:11:50.316631,s_215697,9.31,0
687531,c_84,f,1982,1_459,2022-12-17 00:16:56.629536,s_313173,15.99,1
687532,c_84,f,1982,0_1104,2022-12-17 00:24:14.357525,s_313173,13.21,0
687533,c_84,f,1982,1_688,2022-12-17 00:36:24.148027,s_313173,18.19,1

In [102]:
df.to_csv("final.csv")